print ("9. Cálculo de Área: \n ")
base = float(input("Digite o tamanho da base: "))
altura = float(input("Digite o tamanho da altura: "))
area = ( base*altura)
print ("A area é igual a : {}\n".format(area))